 /* -----------------------------------------------------------\
 |  This code was generated by Oilexer.                        |
 |  Version: 1.0.0.0                                           |
 |-------------------------------------------------------------|
 |  To ensure the code works properly,                         |
 |  please do not make any changes to the file.                |
 |-------------------------------------------------------------|
 |  The specific language is C# (Runtime version: v4.0.30319)  |
 |  Sub-tool Name: Oilexer.CSharpCodeTranslator                |
 |  Sub-tool Version: 1.0.0.0                                  |
 \----------------------------------------------------------- */
using System;
using System.Collections.Generic;

namespace AllenCopeland.Abstraction.Slf._Internal.Cli.TypeIdParser.Tokens
{
    // Module: RootModule
    public partial class TypeIdParserScanData :
        List<TypeIdParserScanData.Entry>
    {
        #region TypeIdParserScanData methods
        public void AddCapture(string capture, TypeIdParserTokens captureSet)
        {
            this.Add(new CaptureEntry(captureSet, capture));
        }
        
        public void AddAssemblyTerminals(AssemblyTerminalCases AssemblyTerminals)
        {
            this.Add(new SubsetEntry(SubsetField.AssemblyTerminalCases, ((int)(AssemblyTerminals))));
        }
        
        public void AddCommonSymbols(CommonSymbolCases CommonSymbols)
        {
            this.Add(new SubsetEntry(SubsetField.CommonSymbolCases, ((int)(CommonSymbols))));
        }
        #endregion // TypeIdParserScanData methods
    }
}
 /* ----------------------------------------------------------------------------------------------\
 |  This file took 00:00:00.0004717 to generate.                                                  |
 |  Date generated: 4/8/2013 7:25:03 PM                                                           |
 |  There were 11 types used by this file                                                         |
 |  System.String, TypeIdParserTokens, System.Void,                                               |
 |  TypeIdParserScanData+CaptureEntry, AssemblyTerminalCases, TypeIdParserScanData+SubsetEntry,   |
 |  TypeIdParserScanData+SubsetField, System.Int32, CommonSymbolCases,                            |
 |  List`1[[TypeIdParserScanData+Entry]], TypeIdParserScanData+Entry                              |
 |------------------------------------------------------------------------------------------------|
 |  There were 1 assemblies referenced:                                                           |
 |  mscorlib                                                                                      |
 \---------------------------------------------------------------------------------------------- */
