 /* -----------------------------------------------------------\
 |  This code was generated by Oilexer.                        |
 |  Version: 1.0.0.0                                           |
 |-------------------------------------------------------------|
 |  To ensure the code works properly,                         |
 |  please do not make any changes to the file.                |
 |-------------------------------------------------------------|
 |  The specific language is C# (Runtime version: v4.0.30319)  |
 |  Sub-tool Name: Oilexer.CSharpCodeTranslator                |
 |  Sub-tool Version: 1.0.0.0                                  |
 \----------------------------------------------------------- */
using System;
using AllenCopeland.Abstraction.Slf._Internal.Cli.TypeIdParser.Tokens;

namespace AllenCopeland.Abstraction.Slf._Internal.Cli.TypeIdParser.Tokens
{
    
    // Module: RootModule
    [FlagsAttribute()]
    internal enum CommonSymbolCases
    {
        /// <summary>
        /// Represents a case where no elements in the current set are selected.
        /// </summary>
        None = 0,

        /// <summary>
        /// <para>Defines a commonsymbol in the TypeIdentity lexer that is '1' characters long.</para>
        /// <para>Actual value: .</para>
        /// </summary>
        /// <remarks>
        /// <para>Original definition: '.':Period;</para>
        /// <para>Defined in "tid.oilexer" on line 240.</para>
        /// </remarks>
        Period = 1,

        /// <summary>
        /// <para>Defines a commonsymbol in the TypeIdentity lexer that is '1' characters long.</para>
        /// <para>Actual value: ,</para>
        /// </summary>
        /// <remarks>
        /// <para>Original definition: ',':Comma;</para>
        /// <para>Defined in "tid.oilexer" on line 241.</para>
        /// </remarks>
        Comma = 2,

        /// <summary>
        /// <para>Defines a commonsymbol in the TypeIdentity lexer that is '1' characters long.</para>
        /// <para>Actual value: [</para>
        /// </summary>
        /// <remarks>
        /// <para>Original definition: '[':LeftSquareBracket;</para>
        /// <para>Defined in "tid.oilexer" on line 242.</para>
        /// </remarks>
        LeftSquareBracket = 4,

        /// <summary>
        /// <para>Defines a commonsymbol in the TypeIdentity lexer that is '1' characters long.</para>
        /// <para>Actual value: ]</para>
        /// </summary>
        /// <remarks>
        /// <para>Original definition: ']':RightSquareBracket;</para>
        /// <para>Defined in "tid.oilexer" on line 243.</para>
        /// </remarks>
        RightSquareBracket = 8,

        /// <summary>
        /// <para>Defines a commonsymbol in the TypeIdentity lexer that is '1' characters long.</para>
        /// <para>Actual value: =</para>
        /// </summary>
        /// <remarks>
        /// <para>Original definition: '=':Equals;</para>
        /// <para>Defined in "tid.oilexer" on line 244.</para>
        /// </remarks>
        Equals = 16,

        /// <summary>
        /// <para>Defines a commonsymbol in the TypeIdentity lexer that is '1' characters long.</para>
        /// <para>Actual value: +</para>
        /// </summary>
        /// <remarks>
        /// <para>Original definition: '+':NestingQualifier;</para>
        /// <para>Defined in "tid.oilexer" on line 245.</para>
        /// </remarks>
        NestingQualifier = 32,

        /// <summary>
        /// <para>Defines a commonsymbol in the TypeIdentity lexer that is '1' characters long.</para>
        /// <para>Actual value: `</para>
        /// </summary>
        /// <remarks>
        /// <para>Original definition: '`':GenericParameterSignal;</para>
        /// <para>Defined in "tid.oilexer" on line 246.</para>
        /// </remarks>
        GenericParameterSignal = 64,

        /// <summary>
        /// <para>Defines a commonsymbol in the TypeIdentity lexer that is '1' characters long.</para>
        /// <para>Actual value: *</para>
        /// </summary>
        /// <remarks>
        /// <para>Original definition: '*':PointerCallout;</para>
        /// <para>Defined in "tid.oilexer" on line 247.</para>
        /// </remarks>
        PointerCallout = 128,

        /// <summary>
        /// <para>Defines a commonsymbol in the TypeIdentity lexer that is '1' characters long.</para>
        /// <para>Actual value: &</para>
        /// </summary>
        /// <remarks>
        /// <para>Original definition: '&':ByRefCallout;</para>
        /// <para>Defined in "tid.oilexer" on line 248.</para>
        /// </remarks>
        ByRefCallout = 256,

        /// <summary>
        /// <para>Defines a commonsymbol in the TypeIdentity lexer that is '1' characters long.</para>
        /// <para>Actual value: "</para>
        /// </summary>
        /// <remarks>
        /// <para>Original definition: '"':QuoteChar;</para>
        /// <para>Defined in "tid.oilexer" on line 249.</para>
        /// </remarks>
        QuoteChar = 512,

        /// <summary>
        /// Represents all the members of the current set of values for CommonSymbols.
        /// </summary>
        All = 1023
    }
}
 /* ----------------------------------------------\
 |  This file took 00:00:00.0003176 to generate.  |
 |  Date generated: 4/8/2013 7:25:03 PM           |
 |  There were 2 types used by this file          |
 |  FlagsAttribute, CommonSymbolCases             |
 |------------------------------------------------|
 |  There were 1 assemblies referenced:           |
 |  mscorlib                                      |
 \---------------------------------------------- */
