 /* -----------------------------------------------------------\
 |  This code was generated by Oilexer.                        |
 |  Version: 1.0.0.0                                           |
 |-------------------------------------------------------------|
 |  To ensure the code works properly,                         |
 |  please do not make any changes to the file.                |
 |-------------------------------------------------------------|
 |  The specific language is C# (Runtime version: v4.0.30319)  |
 |  Sub-tool Name: Oilexer.CSharpCodeTranslator                |
 |  Sub-tool Version: 1.0.0.0                                  |
 \----------------------------------------------------------- */
using System;
using AllenCopeland.Abstraction.Slf._Internal.Cli.TypeIdParser.Tokens;
using AllenCopeland.Abstraction.Slf._Internal.Cli.TypeIdParser.Tokens;

namespace AllenCopeland.Abstraction.Slf._Internal.Cli.TypeIdParser.Tokens
{
    // Module: RootModule
    internal class TIHexQWordTokStateMachine :
        CharStream
    {
        #region TIHexQWordTokStateMachine data members
        /// <summary>
        /// Data member which tracks the current execution path of the state machine.
        /// </summary>
        private int state;
        
        /// <summary>
        /// Data member which denotes the final execution point of the state machine.
        /// </summary>
        /// <remarks>
        /// Only set when an edge in the state machine is hit.
        /// </remarks>
        private bool exitState;
        
        private int exitlength;
        #endregion // TIHexQWordTokStateMachine data members
        #region TIHexQWordTokStateMachine properties
        public bool IsValidEndState
        {
            get
            {
                return this.exitState;
            }
        }
        
        public int BytesConsumed
        {
            get
            {
                return this.exitlength;
            }
        }
        #endregion // TIHexQWordTokStateMachine properties
        #region TIHexQWordTokStateMachine methods
        public bool Next(char @char)
        {
            switch (this.state)
            {
                case 0:
                    if (((('0' <= @char) && (@char <= '9')) || (('A' <= @char) && (@char <= 'F'))) || (('a' <= @char) && (@char <= 'f')))
                        goto MOVETOSTATE1;
                    break;
                case 1:
                    if (((('0' <= @char) && (@char <= '9')) || (('A' <= @char) && (@char <= 'F'))) || (('a' <= @char) && (@char <= 'f')))
                        goto MOVETOSTATE2;
                    break;
                case 2:
                    if (((('0' <= @char) && (@char <= '9')) || (('A' <= @char) && (@char <= 'F'))) || (('a' <= @char) && (@char <= 'f')))
                        goto MOVETOSTATE3;
                    break;
                case 3:
                    if (((('0' <= @char) && (@char <= '9')) || (('A' <= @char) && (@char <= 'F'))) || (('a' <= @char) && (@char <= 'f')))
                        goto MOVETOSTATE4;
                    break;
                case 4:
                    if (((('0' <= @char) && (@char <= '9')) || (('A' <= @char) && (@char <= 'F'))) || (('a' <= @char) && (@char <= 'f')))
                        goto MOVETOSTATE5;
                    break;
                case 5:
                    if (((('0' <= @char) && (@char <= '9')) || (('A' <= @char) && (@char <= 'F'))) || (('a' <= @char) && (@char <= 'f')))
                        goto MOVETOSTATE6;
                    break;
                case 6:
                    if (((('0' <= @char) && (@char <= '9')) || (('A' <= @char) && (@char <= 'F'))) || (('a' <= @char) && (@char <= 'f')))
                        goto MOVETOSTATE7;
                    break;
                case 7:
                    if (((('0' <= @char) && (@char <= '9')) || (('A' <= @char) && (@char <= 'F'))) || (('a' <= @char) && (@char <= 'f')))
                        goto MOVETOSTATE8;
                    break;
                case 8:
                    if (((('0' <= @char) && (@char <= '9')) || (('A' <= @char) && (@char <= 'F'))) || (('a' <= @char) && (@char <= 'f')))
                        goto MOVETOSTATE9;
                    break;
                case 9:
                    if (((('0' <= @char) && (@char <= '9')) || (('A' <= @char) && (@char <= 'F'))) || (('a' <= @char) && (@char <= 'f')))
                        goto MOVETOSTATE10;
                    break;
                case 10:
                    if (((('0' <= @char) && (@char <= '9')) || (('A' <= @char) && (@char <= 'F'))) || (('a' <= @char) && (@char <= 'f')))
                        goto MOVETOSTATE11;
                    break;
                case 11:
                    if (((('0' <= @char) && (@char <= '9')) || (('A' <= @char) && (@char <= 'F'))) || (('a' <= @char) && (@char <= 'f')))
                        goto MOVETOSTATE12;
                    break;
                case 12:
                    if (((('0' <= @char) && (@char <= '9')) || (('A' <= @char) && (@char <= 'F'))) || (('a' <= @char) && (@char <= 'f')))
                        goto MOVETOSTATE13;
                    break;
                case 13:
                    if (((('0' <= @char) && (@char <= '9')) || (('A' <= @char) && (@char <= 'F'))) || (('a' <= @char) && (@char <= 'f')))
                        goto MOVETOSTATE14;
                    break;
                case 14:
                    if (((('0' <= @char) && (@char <= '9')) || (('A' <= @char) && (@char <= 'F'))) || (('a' <= @char) && (@char <= 'f')))
                        goto MOVETOSTATE15;
                    break;
                case 15:
                    if (((('0' <= @char) && (@char <= '9')) || (('A' <= @char) && (@char <= 'F'))) || (('a' <= @char) && (@char <= 'f')))
                        goto MOVETOSTATE16;
                    break;
            }
            return false;
        MOVETOSTATE1:
            this.state = 1;
            goto COMMON_STATEMOVE;
        MOVETOSTATE2:
            this.state = 2;
            goto COMMON_STATEMOVE;
        MOVETOSTATE3:
            this.state = 3;
            goto COMMON_STATEMOVE;
        MOVETOSTATE4:
            this.state = 4;
            goto COMMON_STATEMOVE;
        MOVETOSTATE5:
            this.state = 5;
            goto COMMON_STATEMOVE;
        MOVETOSTATE6:
            this.state = 6;
            goto COMMON_STATEMOVE;
        MOVETOSTATE7:
            this.state = 7;
            goto COMMON_STATEMOVE;
        MOVETOSTATE8:
            this.state = 8;
            goto COMMON_STATEMOVE;
        MOVETOSTATE9:
            this.state = 9;
            goto COMMON_STATEMOVE;
        MOVETOSTATE10:
            this.state = 10;
            goto COMMON_STATEMOVE;
        MOVETOSTATE11:
            this.state = 11;
            goto COMMON_STATEMOVE;
        MOVETOSTATE12:
            this.state = 12;
            goto COMMON_STATEMOVE;
        MOVETOSTATE13:
            this.state = 13;
            goto COMMON_STATEMOVE;
        MOVETOSTATE14:
            this.state = 14;
            goto COMMON_STATEMOVE;
        MOVETOSTATE15:
            this.state = 15;
            goto COMMON_STATEMOVE;
        MOVETOSTATE16:
            this.state = 16;
            this.exitState = true;
            goto TERMINAL_EXIT;
        COMMON_STATEMOVE:
            this.Push(@char);
            return true;
        TERMINAL_EXIT:
            this.Push(@char);
            this.exitlength = this.actualSize;
            return false;
        }
        
        public string GetCapture()
        {
            char[] result = new char[this.exitlength];
            for(int i = 0; (i < this.exitlength); i++)
            {
                result[i] = this.buffer[i];
            }
            return new string(result);
        }
        
        public void Reset()
        {
            this.exitlength = 0;
            this.Purge();
            this.exitState = false;
            this.state = 0;
        }
        
        public void Inject(TypeIdParserScanData data)
        {
            if (this.IsValidEndState)
                data.AddCapture(this.GetCapture(), TypeIdParserTokens.HexQWord);
        }
        #endregion // TIHexQWordTokStateMachine methods
    }
}
 /* ----------------------------------------------------\
 |  This file took 00:00:00.0008147 to generate.        |
 |  Date generated: 4/8/2013 7:25:03 PM                 |
 |  There were 8 types used by this file                |
 |  System.Int32, System.Boolean, System.Char,          |
 |  System.String, System.Void, TypeIdParserScanData,   |
 |  TypeIdParserTokens, CharStream                      |
 |------------------------------------------------------|
 |  There were 1 assemblies referenced:                 |
 |  mscorlib                                            |
 \---------------------------------------------------- */
