 /* -----------------------------------------------------------\
 |  This code was generated by Oilexer.                        |
 |  Version: 1.0.0.0                                           |
 |-------------------------------------------------------------|
 |  To ensure the code works properly,                         |
 |  please do not make any changes to the file.                |
 |-------------------------------------------------------------|
 |  The specific language is C# (Runtime version: v4.0.30319)  |
 |  Sub-tool Name: Oilexer.CSharpCodeTranslator                |
 |  Sub-tool Version: 1.0.0.0                                  |
 \----------------------------------------------------------- */
using AllenCopeland.Abstraction.Slf._Internal.Cli.TypeIdParser.Tokens;
using System;

namespace AllenCopeland.Abstraction.Slf._Internal.Cli.TypeIdParser.Tokens
{
    
    // Module: RootModule
    [Flags]
    internal enum TypeIdParserTokens
    {
        None = 0, 
        
        /// <summary>
        /// Valid token case selector for scanner context awareness.
        /// </summary>
        AssemblyTerminals = 1, 
        
        /// <summary>
        /// Valid token case selector for scanner context awareness.
        /// </summary>
        CommonSymbols = 2, 
        
        /// <summary>
        /// Valid token case selector for scanner context awareness.
        /// </summary>
        CultureIdentifier = 4, 
        
        /// <summary>
        /// Valid token case selector for scanner context awareness.
        /// </summary>
        EndOFile = 8, 
        
        /// <summary>
        /// Valid token case selector for scanner context awareness.
        /// </summary>
        HexByte = 16, 
        
        /// <summary>
        /// Valid token case selector for scanner context awareness.
        /// </summary>
        HexQWord = 32, 
        
        /// <summary>
        /// Valid token case selector for scanner context awareness.
        /// </summary>
        NestedQualifiedAssemblyIdentifier = 64, 
        
        /// <summary>
        /// Valid token case selector for scanner context awareness.
        /// </summary>
        Number = 128, 
        
        /// <summary>
        /// Valid token case selector for scanner context awareness.
        /// </summary>
        QualifiedAssemblyIdentifier = 256, 
        
        /// <summary>
        /// Valid token case selector for scanner context awareness.
        /// </summary>
        QualifiedIdentifier = 512, 
        
        /// <summary>
        /// Valid token case selector for scanner context awareness.
        /// </summary>
        Whitespace = 1024
    }
}
 /* ----------------------------------------------\
 |  This file took 00:00:00.0002269 to generate.  |
 |  Date generated: 4/8/2013 7:25:03 PM           |
 |  There were 1 types used by this file          |
 |  TypeIdParserTokens                            |
 \---------------------------------------------- */
