 /* ----------------------------------------------------------------\
 |  This code was generated by Allen Copeland's Abstraction.        |
 |  Version: 0.5.0.0                                                |
 |------------------------------------------------------------------|
 |  To ensure the code works properly,                              |
 |  please do not make any changes to the file.                     |
 |------------------------------------------------------------------|
 |  The specific language is C♯ (Runtime Version: 4.0.30319.42000)  |
 |  Sub-tool Name: C♯ Code Translator                               |
 |  Sub-tool Version: 1.0.0.0                                       |
 \---------------------------------------------------------------- */
using System;
namespace AllenCopeland.Abstraction.Slf.Ast.Expressions.Linq
{
  /// <summary>
  /// Represents a basic visitor for linq bodies which has a <typeparamref name="TContext"/>
  /// relevant to the visit.
  /// </summary>
  /// <typeparam name="TContext">
  /// Denotes the type of context the members of the <see cref="AllenCopeland.Abstraction.Slf.Ast.Expressions.Linq.ILinqBodyContextualVisitor{TContext}"/>
  /// should receive along with the types that accept the visitor.
  /// </typeparam>
  public interface ILinqBodyContextualVisitor<TContext>
  {
    /// <summary>
    /// Visits the <paramref name="linqBody"/> provided with the given <paramref name="context"/>.
    /// </summary>
    /// <param name="linqBody">
    /// The <see cref="AllenCopeland.Abstraction.Slf.Ast.Expressions.Linq.ILinqSelectBody"/>
    /// relevant to the visit.
    /// </param>
    /// <param name="context">
    /// The <typeparamref name="TContext"/> relevant to the visit.
    /// </param>
    void Visit(ILinqSelectBody linqBody, TContext context);
    /// <summary>
    /// Visits the <paramref name="linqBody"/> provided with the given <paramref name="context"/>.
    /// </summary>
    /// <param name="linqBody">
    /// The <see cref="AllenCopeland.Abstraction.Slf.Ast.Expressions.Linq.ILinqGroupBody"/>
    /// relevant to the visit.
    /// </param>
    /// <param name="context">
    /// The <typeparamref name="TContext"/> relevant to the visit.
    /// </param>
    void Visit(ILinqGroupBody linqBody, TContext context);
    /// <summary>
    /// Visits the <paramref name="linqBody"/> provided with the given <paramref name="context"/>.
    /// </summary>
    /// <param name="linqBody">
    /// The <see cref="AllenCopeland.Abstraction.Slf.Ast.Expressions.Linq.ILinqFusionGroupBody"/>
    /// relevant to the visit.
    /// </param>
    /// <param name="context">
    /// The <typeparamref name="TContext"/> relevant to the visit.
    /// </param>
    void Visit(ILinqFusionGroupBody linqBody, TContext context);
    /// <summary>
    /// Visits the <paramref name="linqBody"/> provided with the given <paramref name="context"/>.
    /// </summary>
    /// <param name="linqBody">
    /// The <see cref="AllenCopeland.Abstraction.Slf.Ast.Expressions.Linq.ILinqFusionSelectBody"/>
    /// relevant to the visit.
    /// </param>
    /// <param name="context">
    /// The <typeparamref name="TContext"/> relevant to the visit.
    /// </param>
    void Visit(ILinqFusionSelectBody linqBody, TContext context);
  };
};
