 /* ----------------------------------------------------------------\
 |  This code was generated by Allen Copeland's Abstraction.        |
 |  Version: 0.5.0.0                                                |
 |------------------------------------------------------------------|
 |  To ensure the code works properly,                              |
 |  please do not make any changes to the file.                     |
 |------------------------------------------------------------------|
 |  The specific language is C♯ (Runtime Version: 4.0.30319.42000)  |
 |  Sub-tool Name: C♯ Code Translator                               |
 |  Sub-tool Version: 1.0.0.0                                       |
 \---------------------------------------------------------------- */
using AllenCopeland.Abstraction.Slf.Abstract;
using AllenCopeland.Abstraction.Slf.Abstract.Members;
using System;
namespace AllenCopeland.Abstraction.Slf.Ast.Statements
{
  /// <summary>
  /// Represents a basic visitor for statements.
  /// </summary>
  public interface IStatementVisitor
  {
    /// <summary>
    /// Visits the <paramref name="statement"/> provided.
    /// </summary>
    /// <param name="statement">
    /// The <see cref="AllenCopeland.Abstraction.Slf.Ast.Statements.IBlockStatement"/> relevant
    /// to the visit.
    /// </param>
    void Visit(IBlockStatement statement);
    /// <summary>
    /// Visits the <paramref name="statement"/> provided.
    /// </summary>
    /// <param name="statement">
    /// The <see cref="AllenCopeland.Abstraction.Slf.Ast.Statements.IBoundChangeEventSignatureHandlerStatement{TEvent,TEventParameter,TEventParent,TSignatureParameter,TSignature,TSignatureParent}"/>
    /// relevant to the visit.
    /// </param>
    void Visit<TEvent, TEventParameter, TEventParent, TSignatureParameter, TSignature, TSignatureParent>(IBoundChangeEventSignatureHandlerStatement<TEvent, TEventParameter, TEventParent, TSignatureParameter, TSignature, TSignatureParent> statement)
      where TEvent:
        IEventSignatureMember<TEvent, TEventParameter, TEventParent>
      where TEventParameter:
        IEventSignatureParameterMember<TEvent, TEventParameter, TEventParent>
      where TEventParent:
        IEventSignatureParent<TEvent, TEventParameter, TEventParent>
      where TSignatureParameter:
        IMethodSignatureParameterMember<TSignatureParameter, TSignature, TSignatureParent>
      where TSignature:
        IMethodSignatureMember<TSignatureParameter, TSignature, TSignatureParent>
      where TSignatureParent:
        ISignatureParent<IGeneralGenericSignatureMemberUniqueIdentifier, TSignature, TSignatureParameter, TSignatureParent>;
    /// <summary>
    /// Visits the <paramref name="statement"/> provided.
    /// </summary>
    /// <param name="statement">
    /// The <see cref="AllenCopeland.Abstraction.Slf.Ast.Statements.IBreakStatement"/> relevant
    /// to the visit.
    /// </param>
    void Visit(IBreakStatement statement);
    /// <summary>
    /// Visits the <paramref name="statement"/> provided.
    /// </summary>
    /// <param name="statement">
    /// The <see cref="AllenCopeland.Abstraction.Slf.Ast.Statements.ICallFusionStatement"/>
    /// relevant to the visit.
    /// </param>
    void Visit(ICallFusionStatement statement);
    /// <summary>
    /// Visits the <paramref name="statement"/> provided.
    /// </summary>
    /// <param name="statement">
    /// The <see cref="AllenCopeland.Abstraction.Slf.Ast.Statements.ICallMethodStatement"/>
    /// relevant to the visit.
    /// </param>
    void Visit(ICallMethodStatement statement);
    /// <summary>
    /// Visits the <paramref name="statement"/> provided.
    /// </summary>
    /// <param name="statement">
    /// The <see cref="AllenCopeland.Abstraction.Slf.Ast.Statements.IChangeEventHandlerStatement"/>
    /// relevant to the visit.
    /// </param>
    void Visit(IChangeEventHandlerStatement statement);
    /// <summary>
    /// Visits the <paramref name="statement"/> provided.
    /// </summary>
    /// <param name="statement">
    /// The <see cref="AllenCopeland.Abstraction.Slf.Ast.Statements.ICommentStatement"/> relevant
    /// to the visit.
    /// </param>
    void Visit(ICommentStatement statement);
    /// <summary>
    /// Visits the <paramref name="statement"/> provided.
    /// </summary>
    /// <param name="statement">
    /// The <see cref="AllenCopeland.Abstraction.Slf.Ast.Statements.IConditionBlockStatement"/>
    /// relevant to the visit.
    /// </param>
    void Visit(IConditionBlockStatement statement);
    /// <summary>
    /// Visits the <paramref name="statement"/> provided.
    /// </summary>
    /// <param name="statement">
    /// The <see cref="AllenCopeland.Abstraction.Slf.Ast.Statements.IConditionContinuationStatement"/>
    /// relevant to the visit.
    /// </param>
    void Visit(IConditionContinuationStatement statement);
    /// <summary>
    /// Visits the <paramref name="statement"/> provided.
    /// </summary>
    /// <param name="statement">
    /// The <see cref="AllenCopeland.Abstraction.Slf.Ast.Statements.IEnumerateSetBreakableBlockStatement"/>
    /// relevant to the visit.
    /// </param>
    void Visit(IEnumerateSetBreakableBlockStatement statement);
    /// <summary>
    /// Visits the <paramref name="statement"/> provided.
    /// </summary>
    /// <param name="statement">
    /// The <see cref="AllenCopeland.Abstraction.Slf.Ast.Statements.IExplicitlyTypedLocalVariableDeclarationStatement"/>
    /// relevant to the visit.
    /// </param>
    void Visit(IExplicitlyTypedLocalVariableDeclarationStatement statement);
    /// <summary>
    /// Visits the <paramref name="statement"/> provided.
    /// </summary>
    /// <param name="statement">
    /// The <see cref="AllenCopeland.Abstraction.Slf.Ast.Statements.IExplicitStringLiteralStatement"/>
    /// relevant to the visit.
    /// </param>
    void Visit(IExplicitStringLiteralStatement statement);
    /// <summary>
    /// Visits the <paramref name="statement"/> provided.
    /// </summary>
    /// <param name="statement">
    /// The <see cref="AllenCopeland.Abstraction.Slf.Ast.Statements.IExpressionStatement"/>
    /// relevant to the visit.
    /// </param>
    void Visit(IExpressionStatement statement);
    /// <summary>
    /// Visits the <paramref name="statement"/> provided.
    /// </summary>
    /// <param name="statement">
    /// The <see cref="AllenCopeland.Abstraction.Slf.Ast.Statements.IGoToCaseStatement"/>
    /// relevant to the visit.
    /// </param>
    void Visit(IGoToCaseStatement statement);
    /// <summary>
    /// Visits the <paramref name="statement"/> provided.
    /// </summary>
    /// <param name="statement">
    /// The <see cref="AllenCopeland.Abstraction.Slf.Ast.Statements.IGoToStatement"/> relevant
    /// to the visit.
    /// </param>
    void Visit(IGoToStatement statement);
    /// <summary>
    /// Visits the <paramref name="statement"/> provided.
    /// </summary>
    /// <param name="statement">
    /// The <see cref="AllenCopeland.Abstraction.Slf.Ast.Statements.IIterationBlockStatement"/>
    /// relevant to the visit.
    /// </param>
    void Visit(IIterationBlockStatement statement);
    /// <summary>
    /// Visits the <paramref name="statement"/> provided.
    /// </summary>
    /// <param name="statement">
    /// The <see cref="AllenCopeland.Abstraction.Slf.Ast.Statements.IIterationDeclarationBlockStatement"/>
    /// relevant to the visit.
    /// </param>
    void Visit(IIterationDeclarationBlockStatement statement);
    /// <summary>
    /// Visits the <paramref name="statement"/> provided.
    /// </summary>
    /// <param name="statement">
    /// The <see cref="AllenCopeland.Abstraction.Slf.Ast.Statements.IJumpStatement"/> relevant
    /// to the visit.
    /// </param>
    void Visit(IJumpStatement statement);
    /// <summary>
    /// Visits the <paramref name="statement"/> provided.
    /// </summary>
    /// <param name="statement">
    /// The <see cref="AllenCopeland.Abstraction.Slf.Ast.Statements.IJumpTarget"/> relevant
    /// to the visit.
    /// </param>
    void Visit(IJumpTarget statement);
    /// <summary>
    /// Visits the <paramref name="statement"/> provided.
    /// </summary>
    /// <param name="statement">
    /// The <see cref="AllenCopeland.Abstraction.Slf.Ast.Statements.ILabelStatement"/> relevant
    /// to the visit.
    /// </param>
    void Visit(ILabelStatement statement);
    /// <summary>
    /// Visits the <paramref name="statement"/> provided.
    /// </summary>
    /// <param name="statement">
    /// The <see cref="AllenCopeland.Abstraction.Slf.Ast.Statements.ILocalDeclarationsStatement"/>
    /// relevant to the visit.
    /// </param>
    void Visit(ILocalDeclarationsStatement statement);
    /// <summary>
    /// Visits the <paramref name="statement"/> provided.
    /// </summary>
    /// <param name="statement">
    /// The <see cref="AllenCopeland.Abstraction.Slf.Ast.Statements.ILockStatement"/> relevant
    /// to the visit.
    /// </param>
    void Visit(ILockStatement statement);
    /// <summary>
    /// Visits the <paramref name="statement"/> provided.
    /// </summary>
    /// <param name="statement">
    /// The <see cref="AllenCopeland.Abstraction.Slf.Ast.Statements.IReturnStatement"/> relevant
    /// to the visit.
    /// </param>
    void Visit(IReturnStatement statement);
    /// <summary>
    /// Visits the <paramref name="statement"/> provided.
    /// </summary>
    /// <param name="statement">
    /// The <see cref="AllenCopeland.Abstraction.Slf.Ast.Statements.ISimpleIterationBlockStatement"/>
    /// relevant to the visit.
    /// </param>
    void Visit(ISimpleIterationBlockStatement statement);
    /// <summary>
    /// Visits the <paramref name="statement"/> provided.
    /// </summary>
    /// <param name="statement">
    /// The <see cref="AllenCopeland.Abstraction.Slf.Ast.Statements.ISwitchCaseBlockStatement"/>
    /// relevant to the visit.
    /// </param>
    void Visit(ISwitchCaseBlockStatement statement);
    /// <summary>
    /// Visits the <paramref name="statement"/> provided.
    /// </summary>
    /// <param name="statement">
    /// The <see cref="AllenCopeland.Abstraction.Slf.Ast.Statements.ISwitchStatement"/> relevant
    /// to the visit.
    /// </param>
    void Visit(ISwitchStatement statement);
    /// <summary>
    /// Visits the <paramref name="statement"/> provided.
    /// </summary>
    /// <param name="statement">
    /// The <see cref="AllenCopeland.Abstraction.Slf.Ast.Statements.IThrowStatement"/> relevant
    /// to the visit.
    /// </param>
    void Visit(IThrowStatement statement);
    /// <summary>
    /// Visits the <paramref name="statement"/> provided.
    /// </summary>
    /// <param name="statement">
    /// The <see cref="AllenCopeland.Abstraction.Slf.Ast.Statements.ITryStatement"/> relevant
    /// to the visit.
    /// </param>
    void Visit(ITryStatement statement);
    /// <summary>
    /// Visits the <paramref name="statement"/> provided.
    /// </summary>
    /// <param name="statement">
    /// The <see cref="AllenCopeland.Abstraction.Slf.Ast.Statements.IUsingBlockStatement"/>
    /// relevant to the visit.
    /// </param>
    void Visit(IUsingBlockStatement statement);
    /// <summary>
    /// Visits the <paramref name="statement"/> provided.
    /// </summary>
    /// <param name="statement">
    /// The <see cref="AllenCopeland.Abstraction.Slf.Ast.Statements.IUsingExpressionBlockStatement"/>
    /// relevant to the visit.
    /// </param>
    void Visit(IUsingExpressionBlockStatement statement);
    /// <summary>
    /// Visits the <paramref name="statement"/> provided.
    /// </summary>
    /// <param name="statement">
    /// The <see cref="AllenCopeland.Abstraction.Slf.Ast.Statements.IWhileStatement"/> relevant
    /// to the visit.
    /// </param>
    void Visit(IWhileStatement statement);
    /// <summary>
    /// Visits the <paramref name="statement"/> provided.
    /// </summary>
    /// <param name="statement">
    /// The <see cref="AllenCopeland.Abstraction.Slf.Ast.Statements.IYieldBreakStatement"/>
    /// relevant to the visit.
    /// </param>
    void Visit(IYieldBreakStatement statement);
    /// <summary>
    /// Visits the <paramref name="statement"/> provided.
    /// </summary>
    /// <param name="statement">
    /// The <see cref="AllenCopeland.Abstraction.Slf.Ast.Statements.IYieldReturnStatement"/>
    /// relevant to the visit.
    /// </param>
    void Visit(IYieldReturnStatement statement);
  };
};
