using AllenCopeland.Abstraction.Slf.Cli.Metadata.Tables;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AllenCopeland.Abstraction.Slf._Internal.Cli.Metadata.Tables
{
    internal interface ICilInstructionVisitor
    {
        void VisitAdd(int instructionOffset);
        void VisitBitwiseAnd(int instructionOffset);
        void VisitBitwiseComplement(int instructionOffset);
        void VisitBitwiseExclusiveOr(int instructionOffset);
        void VisitBitwiseOr(int instructionOffset);
        void VisitBreak(int instructionOffset);
        void VisitCheckedAdd(int instructionOffset);
        void VisitCheckedAddUnSignedOrOrdered(int instructionOffset);
        void VisitCheckedConvertToByteAsInt32(int instructionOffset);
        void VisitCheckedConvertToInt16AsInt32(int instructionOffset);
        void VisitCheckedConvertToInt32AsInt32(int instructionOffset);
        void VisitCheckedConvertToInt64(int instructionOffset);
        void VisitCheckedConvertToNativeInteger(int instructionOffset);
        void VisitCheckedConvertToSByteAsInt32(int instructionOffset);
        void VisitCheckedConvertToUInt16AsInt32(int instructionOffset);
        void VisitCheckedConvertToUInt32AsInt32(int instructionOffset);
        void VisitCheckedConvertToUInt64AsInt64(int instructionOffset);
        void VisitCheckedConvertToUnsignedNativeInteger(int instructionOffset);
        void VisitCheckedConvertUnsignedToByteAsInt32(int instructionOffset);
        void VisitCheckedConvertUnsignedToInt16AsInt32(int instructionOffset);
        void VisitCheckedConvertUnsignedToInt32AsInt32(int instructionOffset);
        void VisitCheckedConvertUnsignedToInt64(int instructionOffset);
        void VisitCheckedConvertUnsignedToNativeInt(int instructionOffset);
        void VisitCheckedConvertUnsignedToNativeUInt(int instructionOffset);
        void VisitCheckedConvertUnsignedToSByteAsInt32(int instructionOffset);
        void VisitCheckedConvertUnsignedToUInt16AsInt32(int instructionOffset);
        void VisitCheckedConvertUnsignedToUInt32AsInt32(int instructionOffset);
        void VisitCheckedConvertUnsignedToUInt64AsInt64(int instructionOffset);
        void VisitCheckedMultiply(int instructionOffset);
        void VisitCheckedMultiplyUnSignedOrOrdered(int instructionOffset);
        void VisitCheckedSubtract(int instructionOffset);
        void VisitCheckedSubtractUnSignedOrOrdered(int instructionOffset);
        void VisitCheckForFiniteNumber(int instructionOffset);
        void VisitConvertUnsignedIntToFloatingPoint(int instructionOffset);
        void VisitDivide(int instructionOffset);
        void VisitDivideUnSignedOrOrdered(int instructionOffset);
        void VisitDuplicateStackItem(int instructionOffset);
        void VisitEndFinallyBlock(int instructionOffset);
        void VisitLoadArg0(int instructionOffset);
        void VisitLoadArg1(int instructionOffset);
        void VisitLoadArg2(int instructionOffset);
        void VisitLoadArg3(int instructionOffset);
        void VisitLoadArrayElementAsByte(int instructionOffset);
        void VisitLoadArrayElementAsDouble(int instructionOffset);
        void VisitLoadArrayElementAsInt16(int instructionOffset);
        void VisitLoadArrayElementAsInt32(int instructionOffset);
        void VisitLoadArrayElementAsInt64(int instructionOffset);
        void VisitLoadArrayElementAsNativeInteger(int instructionOffset);
        void VisitLoadArrayElementAsSByte(int instructionOffset);
        void VisitLoadArrayElementAsSingle(int instructionOffset);
        void VisitLoadArrayElementAsUInt16(int instructionOffset);
        void VisitLoadArrayElementAsUInt32(int instructionOffset);
        void VisitLoadArrayElementReference(int instructionOffset);
        void VisitLoadArrayLength(int instructionOffset);
        void VisitLoadIndirectByte(int instructionOffset);
        void VisitLoadIndirectDouble(int instructionOffset);
        void VisitLoadIndirectInt16(int instructionOffset);
        void VisitLoadIndirectInt32(int instructionOffset);
        void VisitLoadIndirectInt64OrUInt64(int instructionOffset);
        void VisitLoadIndirectNativeInteger(int instructionOffset);
        void VisitLoadIndirectReference(int instructionOffset);
        void VisitLoadIndirectSByte(int instructionOffset);
        void VisitLoadIndirectSingle(int instructionOffset);
        void VisitLoadIndirectUInt16(int instructionOffset);
        void VisitLoadIndirectUInt32(int instructionOffset);
        void VisitLoadInt32ConstantOfEight(int instructionOffset);
        void VisitLoadInt32ConstantOfFive(int instructionOffset);
        void VisitLoadInt32ConstantOfFour(int instructionOffset);
        void VisitLoadInt32ConstantOfMinusOne(int instructionOffset);
        void VisitLoadInt32ConstantOfOne(int instructionOffset);
        void VisitLoadInt32ConstantOfSeven(int instructionOffset);
        void VisitLoadInt32ConstantOfSix(int instructionOffset);
        void VisitLoadInt32ConstantOfThree(int instructionOffset);
        void VisitLoadInt32ConstantOfTwo(int instructionOffset);
        void VisitLoadInt32ConstantOfZero(int instructionOffset);
        void VisitLoadLocal0(int instructionOffset);
        void VisitLoadLocal1(int instructionOffset);
        void VisitLoadLocal2(int instructionOffset);
        void VisitLoadLocal3(int instructionOffset);
        void VisitLoadNullValue(int instructionOffset);
        void VisitMultiply(int instructionOffset);
        void VisitNegate(int instructionOffset);
        void VisitNoOperation(int instructionOffset);
        void VisitPopStackItem(int instructionOffset);
        void VisitRemainder(int instructionOffset);
        void VisitRemainderUnSignedOrOrdered(int instructionOffset);
        void VisitReturn(int instructionOffset);
        void VisitShiftBitsLeft(int instructionOffset);
        void VisitShiftBitsRight(int instructionOffset);
        void VisitShiftBitsRightUnSignedOrOrdered(int instructionOffset);
        void VisitStoreIndirectInt32(int instructionOffset);
        void VisitStoreDoubleArrayElement(int instructionOffset);
        void VisitStoreIndirectDouble(int instructionOffset);
        void VisitStoreIndirectInt16(int instructionOffset);
        void VisitStoreIndirectInt64(int instructionOffset);
        void VisitStoreIndirectNativeInteger(int instructionOffset);
        void VisitStoreIndirectReference(int instructionOffset);
        void VisitStoreIndirectSByte(int instructionOffset);
        void VisitStoreIndirectSingle(int instructionOffset);
        void VisitStoreInt16ArrayElement(int instructionOffset);
        void VisitStoreInt32ArrayElement(int instructionOffset);
        void VisitStoreInt64ArrayElement(int instructionOffset);
        void VisitStoreLocal0(int instructionOffset);
        void VisitStoreLocal1(int instructionOffset);
        void VisitStoreLocal2(int instructionOffset);
        void VisitStoreLocal3(int instructionOffset);
        void VisitStoreNativeIntegerArrayElement(int instructionOffset);
        void VisitStoreReferenceArrayElement(int instructionOffset);
        void VisitStoreSByteArrayElement(int instructionOffset);
        void VisitStoreSingleArrayElement(int instructionOffset);
        void VisitSubtract(int instructionOffset);
        void VisitThrowException(int instructionOffset);
        void VisitUncheckedConvertToByte(int instructionOffset);
        void VisitUncheckedConvertToDouble(int instructionOffset);
        void VisitUncheckedConvertToInt16(int instructionOffset);
        void VisitUncheckedConvertToInt32(int instructionOffset);
        void VisitUncheckedConvertToInt64(int instructionOffset);
        void VisitUncheckedConvertToNativeInteger(int instructionOffset);
        void VisitUncheckedConvertToSByte(int instructionOffset);
        void VisitUncheckedConvertToSingle(int instructionOffset);
        void VisitUncheckedConvertToUInt16(int instructionOffset);
        void VisitUncheckedConvertToUInt32(int instructionOffset);
        void VisitUncheckedConvertToUInt64(int instructionOffset);
        void VisitUncheckedConvertToUnsignedNativeInteger(int instructionOffset);
        void VisitLoadArgumentShortForm(sbyte value, int instructionOffset);
        void VisitLoadInt32ConstantShortForm(sbyte value, int instructionOffset);
        void VisitLoadLocalAddressShortForm(byte value, int instructionOffset);
        void VisitLoadLocalShortForm(byte value, int instructionOffset);
        void VisitLoadArgumentAddressShortForm(byte value, int instructionOffset);
        void VisitStoreLocalShortForm(byte value, int instructionOffset);
        void VisitStoreArgumentShortForm(byte value, int instructionOffset);
        void VisitLoadInt64Constant(long value, int instructionOffset);
        void VisitLoadSingleConstant(float value, int instructionOffset);
        void VisitLoadDoubleConstant(double value, int instructionOffset);
        void VisitLoadInt32Constant(int value, int instructionOffset);
        void VisitBranchIfEqualToShortForm(sbyte relativeInstructionOffset, int instructionOffset);
        void VisitBranchIfFalseShortForm(sbyte relativeInstructionOffset, int instructionOffset);
        void VisitBranchIfGreaterThanOrEqualToUnSignedOrOrderedShortForm(sbyte relativeInstructionOffset, int instructionOffset);
        void VisitBranchIfGreaterThanShortForm(sbyte relativeInstructionOffset, int instructionOffset);
        void VisitBranchIfGreaterThanToOrEqualToShortForm(sbyte relativeInstructionOffset, int instructionOffset);
        void VisitBranchIfGreaterThanUnSignedOrOrderedShortForm(sbyte relativeInstructionOffset, int instructionOffset);
        void VisitBranchIfLessThanOrEqualToUnSignedOrOrderedShortForm(sbyte relativeInstructionOffset, int instructionOffset);
        void VisitBranchIfLessThanOrEqualToShortForm(sbyte relativeInstructionOffset, int instructionOffset);
        void VisitBranchIfLessThanShortForm(sbyte relativeInstructionOffset, int instructionOffset);
        void VisitBranchIfLessThanUnSignedOrOrderedShortForm(sbyte relativeInstructionOffset, int instructionOffset);
        void VisitBranchIfNotEqualToUnSignedOrOrderedShortForm(sbyte relativeInstructionOffset, int instructionOffset);
        void VisitBranchIfTrueShortForm(sbyte relativeInstructionOffset, int instructionOffset);
        void VisitLeaveProtectedBlockShortForm(sbyte relativeInstructionOffset, int instructionOffset);
        void VisitUnconditionalBranchShortForm(sbyte relativeInstructionOffset, int instructionOffset);
        void VisitBranchIfEqualTo(int relativeInstructionOffset, int instructionOffset);
        void VisitBranchIfFalse(int relativeInstructionOffset, int instructionOffset);
        void VisitBranchIfGreaterThan(int relativeInstructionOffset, int instructionOffset);
        void VisitBranchIfGreaterThanOrEqualTo(int relativeInstructionOffset, int instructionOffset);
        void VisitBranchIfGreaterThanOrEqualToUnSignedOrOrdered(int relativeInstructionOffset, int instructionOffset);
        void VisitBranchIfGreaterThanUnSignedOrOrdered(int relativeInstructionOffset, int instructionOffset);
        void VisitBranchIfLessThan(int relativeInstructionOffset, int instructionOffset);
        void VisitBranchIfLessThanOrEqualToUnSignedOrOrdered(int relativeInstructionOffset, int instructionOffset);
        void VisitBranchIfLessThanOrEqualTo(int relativeInstructionOffset, int instructionOffset);
        void VisitBranchIfLessThanUnSignedOrOrdered(int relativeInstructionOffset, int instructionOffset);
        void VisitBranchIfNotEqualToUnSignedOrOrdered(int relativeInstructionOffset, int instructionOffset);
        void VisitBranchIfTrue(int relativeInstructionOffset, int instructionOffset);
        void VisitLeaveProtectedBlock(int relativeInstructionOffset, int instructionOffset);
        void VisitUnconditionalBranch(int relativeInstructionOffset, int instructionOffset);
        void VisitSwitch(int[] targets, int instructionOffset);
        void VisitLoadString(uint userStringOffset, int instructionOffset);
        void VisitAddressCopy(ICliMetadataTableRow targetMetadataRow, int instructionOffset);
        void VisitBox(ICliMetadataTableRow targetMetadataRow, int instructionOffset);
        void VisitCallMethod(ICliMetadataTableRow targetMetadataRow, int instructionOffset);
        void VisitCallMethodIndirect(ICliMetadataTableRow targetMetadataRow, int instructionOffset);
        void VisitCallVirtualMethod(ICliMetadataTableRow targetMetadataRow, int instructionOffset);
        void VisitCastClass(ICliMetadataTableRow targetMetadataRow, int instructionOffset);
        void VisitGetTypedReferenceAddress(ICliMetadataTableRow targetMetadataRow, int instructionOffset);
        void VisitIsInstance(ICliMetadataTableRow targetMetadataRow, int instructionOffset);
        void VisitJumpTo(ICliMetadataTableRow targetMetadataRow, int instructionOffset);
        void VisitLoadArrayElementAddress(ICliMetadataTableRow targetMetadataRow, int instructionOffset);
        void VisitLoadElement(ICliMetadataTableRow targetMetadataRow, int instructionOffset);
        void VisitLoadField(ICliMetadataTableRow targetMetadataRow, int instructionOffset);
        void VisitLoadFieldAddress(ICliMetadataTableRow targetMetadataRow, int instructionOffset);
        void VisitLoadObject(ICliMetadataTableRow targetMetadataRow, int instructionOffset);
        void VisitLoadStaticField(ICliMetadataTableRow targetMetadataRow, int instructionOffset);
        void VisitLoadStaticFieldAddress(ICliMetadataTableRow targetMetadataRow, int instructionOffset);
        void VisitLoadToken(ICliMetadataTableRow targetMetadataRow, int instructionOffset);
        void VisitMakeTypedReference(ICliMetadataTableRow targetMetadataRow, int instructionOffset);
        void VisitNewArray(ICliMetadataTableRow targetMetadataRow, int instructionOffset);
        void VisitNewObject(ICliMetadataTableRow targetMetadataRow, int instructionOffset);
        void VisitStoreElement(ICliMetadataTableRow targetMetadataRow, int instructionOffset);
        void VisitStoreField(ICliMetadataTableRow targetMetadataRow, int instructionOffset);
        void VisitStoreObject(ICliMetadataTableRow targetMetadataRow, int instructionOffset);
        void VisitStoreStaticField(ICliMetadataTableRow targetMetadataRow, int instructionOffset);
        void VisitUnbox(ICliMetadataTableRow targetMetadataRow, int instructionOffset);
        void VisitUnboxAny(ICliMetadataTableRow targetMetadataRow, int instructionOffset);
        /* *
         * Start two-byte instructions.
         * */
        void VisitAllocateLocalMemory(int instructionOffset);
        void VisitCompareEquality(int instructionOffset);
        void VisitCompareGreaterThan(int instructionOffset);
        void VisitCompareGreaterThanUnSignedOrOrdered(int instructionOffset);
        void VisitCompareLessThan(int instructionOffset);
        void VisitCompareLessThanUnSignedOrOrdered(int instructionOffset);
        void VisitCopyMemoryBlock(int instructionOffset);
        void VisitEndFilter(int instructionOffset);
        void VisitGetArgumentList(int instructionOffset);
        void VisitInitializeMemoryBlock(int instructionOffset);
        void VisitPointerReferenceMayBeUnaligned(int instructionOffset);
        void VisitTailCallModifier(int instructionOffset);
        void VisitVolatilePointerReference(int instructionOffset);
        void VisitLoadArgument(short index, int instructionOffset);
        void VisitLoadArgumentAddress(short index, int instructionOffset);
        void VisitLoadLocal(short index, int instructionOffset);
        void VisitLoadLocalAddress(short index, int instructionOffset);
        void VisitStoreArgument(short index, int instructionOffset);
        void VisitStoreLocal(short index, int instructionOffset);
        void VisitConstrainedCallVirtModifier(ICliMetadataTableRow targetMetadataRow, int instructionOffset);
        void VisitInitializeObject(ICliMetadataTableRow targetMetadataRow, int instructionOffset);
        void VisitLoadMethodPointer(ICliMetadataTableRow targetMetadataRow, int instructionOffset);
        void VisitLoadVirtualMethodPointer(ICliMetadataTableRow targetMetadataRow, int instructionOffset);
    }
}
