 /* ----------------------------------------------------------------\
 |  This code was generated by Allen Copeland's Abstraction.        |
 |  Version: 0.5.0.0                                                |
 |------------------------------------------------------------------|
 |  To ensure the code works properly,                              |
 |  please do not make any changes to the file.                     |
 |------------------------------------------------------------------|
 |  The specific language is C♯ (Runtime Version: 4.0.30319.42000)  |
 |  Sub-tool Name: C♯ Code Translator                               |
 |  Sub-tool Version: 1.0.0.0                                       |
 \---------------------------------------------------------------- */
using AllenCopeland.Abstraction.Slf.Abstract;
using System;
namespace AllenCopeland.Abstraction.Slf.Ast.Expressions
{
  /// <summary>
  /// Represents a basic visitor for primitives which has a <typeparamref name="TContext"/>
  /// relevant to the visit.
  /// </summary>
  /// <typeparam name="TContext">
  /// Denotes the type of context the members of the <see cref="AllenCopeland.Abstraction.Slf.Ast.Expressions.IPrimitiveContextualVisitor{TContext}"/>
  /// should receive along with the types that accept the visitor.
  /// </typeparam>
  public interface IPrimitiveContextualVisitor<TContext>
  {
    /// <summary>
    /// Visits the <paramref name="primitive"/> provided with the given <paramref name="context"/>.
    /// </summary>
    /// <param name="primitive">
    /// The <see cref="AllenCopeland.Abstraction.Slf.Ast.Expressions.IPrimitiveExpression{T}"/>
    /// of <see cref="AllenCopeland.Abstraction.Slf.Abstract.IType"/> relevant to the visit.
    /// </param>
    /// <param name="context">
    /// The <typeparamref name="TContext"/> relevant to the visit.
    /// </param>
    void Visit(IPrimitiveExpression<IType> primitive, TContext context);
    /// <summary>
    /// Visits the <paramref name="primitive"/> provided with the given <paramref name="context"/>.
    /// </summary>
    /// <param name="primitive">
    /// The <see cref="AllenCopeland.Abstraction.Slf.Ast.Expressions.IPrimitiveExpression{T}"/>
    /// of <see cref="System.Boolean"/> relevant to the visit.
    /// </param>
    /// <param name="context">
    /// The <typeparamref name="TContext"/> relevant to the visit.
    /// </param>
    void Visit(IPrimitiveExpression<bool> primitive, TContext context);
    /// <summary>
    /// Visits the <paramref name="primitive"/> provided with the given <paramref name="context"/>.
    /// </summary>
    /// <param name="primitive">
    /// The <see cref="AllenCopeland.Abstraction.Slf.Ast.Expressions.IPrimitiveExpression{T}"/>
    /// of <see cref="System.Byte"/> relevant to the visit.
    /// </param>
    /// <param name="context">
    /// The <typeparamref name="TContext"/> relevant to the visit.
    /// </param>
    void Visit(IPrimitiveExpression<byte> primitive, TContext context);
    /// <summary>
    /// Visits the <paramref name="primitive"/> provided with the given <paramref name="context"/>.
    /// </summary>
    /// <param name="primitive">
    /// The <see cref="AllenCopeland.Abstraction.Slf.Ast.Expressions.IPrimitiveExpression{T}"/>
    /// of <see cref="System.Char"/> relevant to the visit.
    /// </param>
    /// <param name="context">
    /// The <typeparamref name="TContext"/> relevant to the visit.
    /// </param>
    void Visit(IPrimitiveExpression<char> primitive, TContext context);
    /// <summary>
    /// Visits the <paramref name="primitive"/> provided with the given <paramref name="context"/>.
    /// </summary>
    /// <param name="primitive">
    /// The <see cref="AllenCopeland.Abstraction.Slf.Ast.Expressions.IPrimitiveExpression{T}"/>
    /// of <see cref="System.Decimal"/> relevant to the visit.
    /// </param>
    /// <param name="context">
    /// The <typeparamref name="TContext"/> relevant to the visit.
    /// </param>
    void Visit(IPrimitiveExpression<decimal> primitive, TContext context);
    /// <summary>
    /// Visits the <paramref name="primitive"/> provided with the given <paramref name="context"/>.
    /// </summary>
    /// <param name="primitive">
    /// The <see cref="AllenCopeland.Abstraction.Slf.Ast.Expressions.IPrimitiveExpression{T}"/>
    /// of <see cref="System.Double"/> relevant to the visit.
    /// </param>
    /// <param name="context">
    /// The <typeparamref name="TContext"/> relevant to the visit.
    /// </param>
    void Visit(IPrimitiveExpression<double> primitive, TContext context);
    /// <summary>
    /// Visits the <paramref name="primitive"/> provided with the given <paramref name="context"/>.
    /// </summary>
    /// <param name="primitive">
    /// The <see cref="AllenCopeland.Abstraction.Slf.Ast.Expressions.IPrimitiveExpression{T}"/>
    /// of <see cref="System.Int16"/> relevant to the visit.
    /// </param>
    /// <param name="context">
    /// The <typeparamref name="TContext"/> relevant to the visit.
    /// </param>
    void Visit(IPrimitiveExpression<short> primitive, TContext context);
    /// <summary>
    /// Visits the <paramref name="primitive"/> provided with the given <paramref name="context"/>.
    /// </summary>
    /// <param name="primitive">
    /// The <see cref="AllenCopeland.Abstraction.Slf.Ast.Expressions.IPrimitiveExpression{T}"/>
    /// of <see cref="System.Int32"/> relevant to the visit.
    /// </param>
    /// <param name="context">
    /// The <typeparamref name="TContext"/> relevant to the visit.
    /// </param>
    void Visit(IPrimitiveExpression<int> primitive, TContext context);
    /// <summary>
    /// Visits the <paramref name="primitive"/> provided with the given <paramref name="context"/>.
    /// </summary>
    /// <param name="primitive">
    /// The <see cref="AllenCopeland.Abstraction.Slf.Ast.Expressions.IPrimitiveExpression{T}"/>
    /// of <see cref="System.Int64"/> relevant to the visit.
    /// </param>
    /// <param name="context">
    /// The <typeparamref name="TContext"/> relevant to the visit.
    /// </param>
    void Visit(IPrimitiveExpression<long> primitive, TContext context);
    /// <summary>
    /// Visits the <paramref name="primitive"/> provided with the given <paramref name="context"/>.
    /// </summary>
    /// <param name="primitive">
    /// The <see cref="AllenCopeland.Abstraction.Slf.Ast.Expressions.IPrimitiveExpression{T}"/>
    /// of <see cref="System.SByte"/> relevant to the visit.
    /// </param>
    /// <param name="context">
    /// The <typeparamref name="TContext"/> relevant to the visit.
    /// </param>
    void Visit(IPrimitiveExpression<sbyte> primitive, TContext context);
    /// <summary>
    /// Visits the <paramref name="primitive"/> provided with the given <paramref name="context"/>.
    /// </summary>
    /// <param name="primitive">
    /// The <see cref="AllenCopeland.Abstraction.Slf.Ast.Expressions.IPrimitiveExpression{T}"/>
    /// of <see cref="System.Single"/> relevant to the visit.
    /// </param>
    /// <param name="context">
    /// The <typeparamref name="TContext"/> relevant to the visit.
    /// </param>
    void Visit(IPrimitiveExpression<float> primitive, TContext context);
    /// <summary>
    /// Visits the <paramref name="primitive"/> provided with the given <paramref name="context"/>.
    /// </summary>
    /// <param name="primitive">
    /// The <see cref="AllenCopeland.Abstraction.Slf.Ast.Expressions.IPrimitiveExpression{T}"/>
    /// of <see cref="System.String"/> relevant to the visit.
    /// </param>
    /// <param name="context">
    /// The <typeparamref name="TContext"/> relevant to the visit.
    /// </param>
    void Visit(IPrimitiveExpression<string> primitive, TContext context);
    /// <summary>
    /// Visits the <paramref name="primitive"/> provided with the given <paramref name="context"/>.
    /// </summary>
    /// <param name="primitive">
    /// The <see cref="AllenCopeland.Abstraction.Slf.Ast.Expressions.IPrimitiveExpression{T}"/>
    /// of <see cref="System.UInt16"/> relevant to the visit.
    /// </param>
    /// <param name="context">
    /// The <typeparamref name="TContext"/> relevant to the visit.
    /// </param>
    void Visit(IPrimitiveExpression<ushort> primitive, TContext context);
    /// <summary>
    /// Visits the <paramref name="primitive"/> provided with the given <paramref name="context"/>.
    /// </summary>
    /// <param name="primitive">
    /// The <see cref="AllenCopeland.Abstraction.Slf.Ast.Expressions.IPrimitiveExpression{T}"/>
    /// of <see cref="System.UInt32"/> relevant to the visit.
    /// </param>
    /// <param name="context">
    /// The <typeparamref name="TContext"/> relevant to the visit.
    /// </param>
    void Visit(IPrimitiveExpression<uint> primitive, TContext context);
    /// <summary>
    /// Visits the <paramref name="primitive"/> provided with the given <paramref name="context"/>.
    /// </summary>
    /// <param name="primitive">
    /// The <see cref="AllenCopeland.Abstraction.Slf.Ast.Expressions.IPrimitiveExpression{T}"/>
    /// of <see cref="System.UInt64"/> relevant to the visit.
    /// </param>
    /// <param name="context">
    /// The <typeparamref name="TContext"/> relevant to the visit.
    /// </param>
    void Visit(IPrimitiveExpression<ulong> primitive, TContext context);
  };
};
