 /* ----------------------------------------------------------\
 |  This code was generated by Allen Copeland's Abstraction.  |
 |  Version: 0.5.0.0                                          |
 |------------------------------------------------------------|
 |  To ensure the code works properly,                        |
 |  please do not make any changes to the file.               |
 |------------------------------------------------------------|
 |  The specific language is C♯                               |
 |  Sub-tool Name: C♯ Code Translator                         |
 |  Sub-tool Version: 1.0.0.0                                 |
 \---------------------------------------------------------- */
using AllenCopeland.Abstraction.Utilities.Collections;
using System;
namespace AllenCopeland.Abstraction.Slf.Cli.Metadata.Tables
{
    public interface ICliMetadataManifestResourceMutableTable :
        IControlledCollection<ICliMetadataManifestResourceMutableTableRow>
    {
        void Add(ICliMetadataManifestResourceMutableTableRow manifestResourceToAdd);
        void Remove(ICliMetadataManifestResourceMutableTableRow manifestResourceToRemove);
    };
};
