using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace AllenCopeland.Abstraction.Slf._Internal.Metadata
{
    /// <summary>
    /// The <see cref="ArgumentException"/> message.
    /// </summary>
    internal enum ExceptionMessageId
    {
        /// <summary>
        /// Constraints on generic parameter {0} failed on the type provided ({1}).
        /// </summary>
        GenericParameterFailureException,
        /// <summary>
        /// Invalid target container type, must be generated by a compiler.
        /// </summary>
        TypeMustBeCompilerGenerated,
        /// <summary>
        /// Provided type must be the child of a generic.
        /// </summary>
        TypeMustBeGenericChild,
        /// <summary>
        /// Invalid target container type, must be a static (abstract
        /// sealed) class.
        /// </summary>
        TypeMustBeStaticClass,
        /// <summary>
        /// Type not generic.
        /// </summary>
        TypeNotGeneric,
        /// <summary>
        /// Type provided represents an informational type, and must
        /// contain only the generic arguments of declaring generic
        /// type.
        /// </summary>
        TypeParameterInfoError,
        /// <summary>
        /// Unknown argument identifier provided.
        /// </summary>
        UnknownArgument,
        /// <summary>
        /// Unknown argument message identifier provided.
        /// </summary>
        UnknownArgumentMessage,
    }
}
