 /* ----------------------------------------------------------------\
 |  This code was generated by Allen Copeland's Abstraction.        |
 |  Version: 0.5.0.0                                                |
 |------------------------------------------------------------------|
 |  To ensure the code works properly,                              |
 |  please do not make any changes to the file.                     |
 |------------------------------------------------------------------|
 |  The specific language is C♯ (Runtime Version: 4.0.30319.42000)  |
 |  Sub-tool Name: C♯ Code Translator                               |
 |  Sub-tool Version: 1.0.0.0                                       |
 \---------------------------------------------------------------- */
using AllenCopeland.Abstraction.Slf.Ast.Members;
namespace AllenCopeland.Abstraction.Slf.Ast
{
  /// <summary>
  /// Represents a basic visitor for intermediate trees.
  /// </summary>
  public interface IIntermediateTreeVisitor :
    IIntermediateCodeVisitor, 
    IIntermediateDeclarationVisitor, 
    IIntermediateMemberVisitor, 
    IIntermediateTypeVisitor
  {
  };
};
