 /* ----------------------------------------------------------------\
 |  This code was generated by Allen Copeland's Abstraction.        |
 |  Version: 0.5.0.0                                                |
 |------------------------------------------------------------------|
 |  To ensure the code works properly,                              |
 |  please do not make any changes to the file.                     |
 |------------------------------------------------------------------|
 |  The specific language is C♯ (Runtime Version: 4.0.30319.42000)  |
 |  Sub-tool Name: C♯ Code Translator                               |
 |  Sub-tool Version: 1.0.0.0                                       |
 \---------------------------------------------------------------- */
using AllenCopeland.Abstraction.Slf.Abstract;
using AllenCopeland.Abstraction.Slf.Ast.Members;
namespace AllenCopeland.Abstraction.Slf.Ast
{
  /// <summary>
  /// Represents a basic visitor for intermediate types which yields a result of <typeparamref name="TResult"/>.
  /// </summary>
  /// <typeparam name="TResult">
  /// Denotes the type of result the members of the <see cref="AllenCopeland.Abstraction.Slf.Ast.IIntermediateTypeVisitor{TResult}"/>
  /// should yield.
  /// </typeparam>
  public interface IIntermediateTypeVisitor<TResult>
  {
    /// <summary>
    /// Returns a <typeparamref name="TResult"/> after it visits the <paramref name="intermediateType"/>
    /// provided.
    /// </summary>
    /// <param name="intermediateType">
    /// The <see cref="AllenCopeland.Abstraction.Slf.Ast.IIntermediateClassType"/> relevant
    /// to the visit.
    /// </param>
    /// <returns>
    /// Returns the value of <typeparamref name="TResult"/> relative to the implementation
    /// of the visitor.
    /// </returns>
    TResult Visit(IIntermediateClassType intermediateType);
    /// <summary>
    /// Returns a <typeparamref name="TResult"/> after it visits the <paramref name="intermediateType"/>
    /// provided.
    /// </summary>
    /// <param name="intermediateType">
    /// The <see cref="AllenCopeland.Abstraction.Slf.Ast.IIntermediateDelegateType"/> relevant
    /// to the visit.
    /// </param>
    /// <returns>
    /// Returns the value of <typeparamref name="TResult"/> relative to the implementation
    /// of the visitor.
    /// </returns>
    TResult Visit(IIntermediateDelegateType intermediateType);
    /// <summary>
    /// Returns a <typeparamref name="TResult"/> after it visits the <paramref name="intermediateType"/>
    /// provided.
    /// </summary>
    /// <param name="intermediateType">
    /// The <see cref="AllenCopeland.Abstraction.Slf.Ast.IIntermediateEnumType"/> relevant
    /// to the visit.
    /// </param>
    /// <returns>
    /// Returns the value of <typeparamref name="TResult"/> relative to the implementation
    /// of the visitor.
    /// </returns>
    TResult Visit(IIntermediateEnumType intermediateType);
    /// <summary>
    /// Returns a <typeparamref name="TResult"/> after it visits the <paramref name="intermediateType"/>
    /// provided.
    /// </summary>
    /// <param name="intermediateType">
    /// The <see cref="AllenCopeland.Abstraction.Slf.Ast.IIntermediateInterfaceType"/> relevant
    /// to the visit.
    /// </param>
    /// <returns>
    /// Returns the value of <typeparamref name="TResult"/> relative to the implementation
    /// of the visitor.
    /// </returns>
    TResult Visit(IIntermediateInterfaceType intermediateType);
    /// <summary>
    /// Returns a <typeparamref name="TResult"/> after it visits the <paramref name="intermediateType"/>
    /// provided.
    /// </summary>
    /// <param name="intermediateType">
    /// The <see cref="AllenCopeland.Abstraction.Slf.Ast.IIntermediateStructType"/> relevant
    /// to the visit.
    /// </param>
    /// <returns>
    /// Returns the value of <typeparamref name="TResult"/> relative to the implementation
    /// of the visitor.
    /// </returns>
    TResult Visit(IIntermediateStructType intermediateType);
    /// <summary>
    /// Returns a <typeparamref name="TResult"/> after it visits the <paramref name="intermediateType"/>
    /// provided.
    /// </summary>
    /// <param name="intermediateType">
    /// The <see cref="AllenCopeland.Abstraction.Slf.Ast.Members.IIntermediateGenericParameter{TGenericParameter,TIntermediateGenericParameter,TParent,TIntermediateParent}"/>
    /// relevant to the visit.
    /// </param>
    /// <returns>
    /// Returns the value of <typeparamref name="TResult"/> relative to the implementation
    /// of the visitor.
    /// </returns>
    TResult Visit<TGenericParameter, TIntermediateGenericParameter, TParent, TIntermediateParent>(IIntermediateGenericParameter<TGenericParameter, TIntermediateGenericParameter, TParent, TIntermediateParent> intermediateType)
      where TGenericParameter:
        IGenericParameter<TGenericParameter, TParent>
      where TIntermediateGenericParameter:
        TGenericParameter,
        IIntermediateGenericParameter<TGenericParameter, TIntermediateGenericParameter, TParent, TIntermediateParent>
      where TParent:
        IGenericParamParent<TGenericParameter, TParent>
      where TIntermediateParent:
        TParent,
        IIntermediateGenericParameterParent<TGenericParameter, TIntermediateGenericParameter, TParent, TIntermediateParent>;
  };
};
