using System;
using AllenCopeland.Abstraction.Slf.Abstract;
/*---------------------------------------------------------------------\
 | Copyright © 2008-2015 Allen C. [Alexander Morou] Copeland Jr.        |
 |----------------------------------------------------------------------|
 | The Abstraction Project's code is provided under a contract-release  |
 | basis.  DO NOT DISTRIBUTE and do not use beyond the contract terms.  |
 \-------------------------------------------------------------------- */

namespace AllenCopeland.Abstraction.Slf.Compilers
{
    /// <summary>
    /// Provides the abstract variant of the anonymous type
    /// pattern aid used to specify the patterns used by 
    /// anonymous types and their members.
    /// </summary>
    public abstract class AnonymousTypePatternAid :
        IAnonymousTypePatternAid
    {
        #region IAnonymousTypePatternAid Members

        /// <summary>
        /// Obtains the <see cref="String"/> that represents
        /// a given <see cref="IAnonymousType"/>'s name.
        /// </summary>
        /// <param name="target">The target <see cref="IAnonymousType"/>
        /// from which to generate the name.</param>
        /// <returns>A <see cref="String"/> which represents the name
        /// of the <see cref="IAnonymousType"/>.</returns>
        public abstract string GetTypeName(IAnonymousType target);

        /// <summary>
        /// Obtains a <see cref="String"/> that represents 
        /// a given <see cref="IAnonymousType"/>'s generic parameter's
        /// name.
        /// </summary>
        /// <param name="associatedMember">The <see cref="AnonymousTypeMember"/>
        /// to obtain the generic parameter name of.</param>
        /// <returns>A <see cref="System.String"/> instance
        /// representing the type-parameter's name.</returns>
        public abstract string GetTypeParameter(AnonymousTypeMember associatedMember);

        /// <summary>
        /// Obtains a <see cref="String"/> that represents
        /// a given <see cref="IAnonymousType"/>'s backing
        /// field name.
        /// </summary>
        /// <param name="associatedMember">The
        /// <see cref="AnonymousTypeMember"/> to obtain the
        /// field name of.</param>
        /// <returns>A <see cref="System.String"/> instance
        /// representing the field's name.</returns>
        public abstract string GetAnonymousField(AnonymousTypeMember associatedMember);

        /// <summary>
        /// Obtains a <see cref="String"/> that represents
        /// a given <see cref="IAnonymousType"/>'s property
        /// name.
        /// </summary>
        /// <param name="associatedMember">The
        /// <see cref="AnonymousTypeMember"/> to obtain the
        /// property name of.</param>
        /// <returns>A <see cref="System.String"/> instance
        /// representing the property's name.</returns>
        public abstract string GetAutoGeneratedProperty(AnonymousTypeMember associatedMember);

        #endregion
    }
}
